version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: duyadmin
      MYSQL_PASSWORD: duyadmin

  phpadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:

  wordpress:
    depends_on:
      - db
    volumes:
      - ./htdocs:/var/www/html
      - ./lib:/var/www/lib
      - ./vhost:/etc/apache2/sites-enabled
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db
  node:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: wp_sage_node
    volumes:
      - ./wordpress/wp-content/themes/sage:/var/www/html/wp-content/themes/sage
    working_dir: /var/www/html/wp-content/themes/sage
    command: "sleep infinity"
